CXX = g++ -std=c++11
#CXXFLAGS = 

DSTS = scheduler floor elevator display test_sendPacket test

all: $(DSTS)

clean:
	rm $(DSTS)

elevator: elevator.cpp
scheduler: scheduler.cpp
floor: floor.cpp
display: display.cpp

test_sendPacket: test_sendPacket.cpp
test: test.cpp