CC = gcc -std=c11
#CFLAGS = 

DSTS = scheduler floor elevator display test_sendPacket test display_and_floor

all: $(DSTS)

clean:
	rm $(DSTS)

elevator: elevator.cpp
scheduler: scheduler.cpp
floor: floor.cpp
display: display.cpp
display_and_floor: display_and_floor.cpp

test_sendPacket: test_sendPacket.cpp
test: test.cpp
