CXX = g++ -std=c++11
#CXXFLAGS = 

DSTS = scheduler floor elevator test

all: $(DSTS)

clean:
	rm $(DSTS)

elevator: elevator.cpp
scheduler: scheduler.cpp
floor: floor.cpp
test: test.cpp scheduler.cpp